name: Test

on:
  push:
    branches: [ main-2 ]
  pull_request:
    branches: [ main-2 ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Test Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
